// ══════════════════════════════════════
// LIFECOMPARE PRO — DATA FILE
// Update this file when adding new plans
// ══════════════════════════════════════

const PLANS = [
  {
    id: 1,
    company: "Aditya Birla Sun Life Insurance",
    companyShort: "ABSLI",
    bestFor: "Best for: Disability protection (free WOP inbuilt)",
    plan: "Super Term Plan",
    uin: "109N153V02",
    csr: 98.65,
    csrPending: false,
    entryAge: "18 – 65 yrs",
    maxMaturity: "85 yrs",
    minSA: "₹25 Lakh",
    maxSA: "Unlimited",
    premiumPay: "Regular / Limited / Single",
    limitedPayTerms: "5,7,10,12,15,20 yrs / Pay till 60",
    premiumModes: "Annual / Semi-Annual / Quarterly / Monthly",
    deathBenefit: "Lump Sum / Monthly Income / Lump Sum + Income",
    // Feature flags (used for filter + tags)
    wholeLife: false,
    terminalIllness: true,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: true,
    returnOfPremium: true,
    jointLife: false,
    premiumBreak: true,
    smartExit: true,
    spouseCover: false,
    lifeStage: true,
    // Display tags on card
    tags: [
      { label: "Terminal Illness ✓", type: "yes" },
      { label: "WOP Disability ✓", type: "yes" },
      { label: "42 CI Cover ✓", type: "yes" },
      { label: "Early Exit Value ✓", type: "yes" },
      { label: "Premium Break ✓", type: "yes" },
      { label: "ROP (Option 3) ✓", type: "yes" },
    ],
    keyStats: [
      { val: "85 yrs", lbl: "Max Cover" },
      { val: "42 CIs", lbl: "CI Options" },
      { val: "3 Options", lbl: "Plan Types" },
    ],
    salesPitch: "ABSLI Super Term Plan is built for the discerning buyer who wants more than just death cover. Its inbuilt WOP on disability (not a rider — free!) is unique among private insurers. The Early Exit Value lets you walk away at age 60 with 100% premiums back — no extra cost. For sales professionals, it's the plan that answers the 'what if I survive?' objection without upselling.",
    keyFeatures: [
      "3 Plan Options: Level / Increasing (5% p.a.) / Level + ROP",
      "Terminal Illness (inbuilt): 50% SA immediately; future premiums waived",
      "WOP on ATPD (inbuilt, free) — not a rider, up to age 70",
      "ACI Benefit (optional): 42 Critical Illnesses, 90-day waiting period",
      "Enhanced Life Stage Protection: Marriage / Child / Home Loan (no medical)",
      "Early Exit Value: 100% premiums back between age 60–70 (after 30 policy yrs)",
      "Premium Break: After 5 policy years",
      "Insta Payment: Accelerated claim within 1 working day"
    ],
    womenDiscount: "Lower rates vs male lives",
    salariedDiscount: "See ABSLI Salaried Term Plan",
    calcUrl: "https://lifeinsurance.adityabirlacapital.com/term-insurance/absli-super-term-plan/",
    brochureUrl: "https://lifeinsurance.adityabirlacapital.com/uploads/ABSLI_Super_Term_Plan_V01_Brochure_8b9b57ef0d.pdf",
    lastUpdated: "July 2026 (monthly review)"
  },
  {
    id: 2,
    company: "HDFC Life Insurance Company Ltd.",
    companyShort: "HDFC Life",
    bestFor: "Best for: Couples (free spouse cover)",
    plan: "Click 2 Protect Supreme Plus",
    uin: "101N189V03",
    csr: 99.72,
    csrPending: false,
    entryAge: "18 – 65 yrs (Life Plus/Goal) / 18 – 84 yrs (Life)",
    maxMaturity: "85 yrs",
    minSA: "₹10,000",
    maxSA: "Unlimited",
    premiumPay: "Single / Regular / Limited",
    limitedPayTerms: "2 years to PT–1",
    premiumModes: "Annual / Half-yearly / Quarterly / Monthly",
    deathBenefit: "Lump Sum / Instalment (5–15 yrs, nominee's choice)",
    wholeLife: false,
    terminalIllness: true,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: true,
    returnOfPremium: true,
    jointLife: false,
    premiumBreak: true,
    smartExit: true,
    spouseCover: true,
    lifeStage: true,
    tags: [
      { label: "Spouse Cover ✓", type: "yes" },
      { label: "Terminal Illness ✓", type: "yes" },
      { label: "Smart Exit ✓", type: "yes" },
      { label: "ROP Optional ✓", type: "yes" },
      { label: "Parent Secure ✓", type: "yes" },
      { label: "WOP CI & Disability ✓", type: "yes" },
    ],
    keyStats: [
      { val: "99.68%", lbl: "CSR FY25" },
      { val: "₹5L", lbl: "Instant Claim" },
      { val: "85 yrs", lbl: "Max Cover" },
    ],
    salesPitch: "HDFC Life Click 2 Protect Supreme Plus is the most feature-complete term plan in the market. Supreme Plus adds Education Income Benefit, WOP on husband accidental death (female lives) and enhanced Life Stage benefit over the previous Supreme plan. Spouse Cover (inbuilt, free) and Parent Secure payout remain standout features. Ideal for comprehensive family protection.",
    keyFeatures: [
      '3 Variants: Life / Life Plus (ADB inbuilt) / Life Goal (reducing cover for liability)',
      'Terminal Illness: Accelerates up to ₹2 Cr immediately on diagnosis (capped at age 80)',
      'Spouse Cover: 50% SA for outstanding term — inbuilt, no extra premium',
      'Education Income Benefit: Regular income for child education (NEW in Supreme Plus)',
      'Parent Secure: Death Benefit paid as lifelong income to parent/grandparent nominees',
      'Life Stage: Marriage / Child ×2 / Loan options — enhanced benefit vs Supreme',
      'Premium Break: After 5 yrs | Women: pregnancy or after husband accidental death',
      'Smart Exit: After 25 policy years — 100% premiums returned (zero-cost exit)',
      'WOP on husband accidental death: For female lives only (NEW in Supreme Plus)',
      'Renewability at Maturity: Available under Regular Pay, Life/Life Plus variants'
    ],
    womenDiscount: "15% on base premium rates",
    salariedDiscount: "10% on first year premium",
    calcUrl: "https://www.hdfclife.com/term-insurance-plans/click-2-protect-supreme-plus",
    brochureUrl: "https://www.hdfclife.com/content/dam/hdfclifeinsurancecompany/products-page/brochure-pdf/HDFC-Life-click-2-protect-supreme-plus.pdf",
    lastUpdated: "July 2026 (monthly review) | CSR: FY 2024-25"
  },
  {
    id: 3,
    company: "Axis Max Life Insurance Co. Ltd.",
    companyShort: "Axis Max Life",
    bestFor: "Best for: Maximum exit value (up to 200% premiums back)",
    plan: "Smart Term Plan Plus",
    uin: "104N127V05",
    csr: 99.65,
    csrPending: false,
    entryAge: "18 – 65 yrs",
    maxMaturity: "100 yrs",
    minSA: "₹25 Lakh",
    maxSA: "Unlimited",
    premiumPay: "Regular / Limited / Single",
    limitedPayTerms: "5,7,10,12,15,20 yrs / Pay till 60",
    premiumModes: "Annual / Half-yearly / Quarterly / Monthly",
    deathBenefit: "Lump Sum / Monthly Income (Level or +10% / 3yrs) / Lump Sum + Income",
    wholeLife: true,
    terminalIllness: true,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: true,
    returnOfPremium: true,
    jointLife: false,
    premiumBreak: true,
    smartExit: true,
    spouseCover: false,
    lifeStage: true,
    tags: [
      { label: "Whole Life 100 yrs ✓", type: "yes" },
      { label: "200% SEV ✓", type: "amber" },
      { label: "3-hr Claim ⚡", type: "amber" },
      { label: "Cover from 3 yrs ✓", type: "yes" },
      { label: "Policy Loan ✓", type: "yes" },
      { label: "Maternity Cover ✓", type: "yes" },
    ],
    keyStats: [
      { val: "100 yrs", lbl: "Max Cover" },
      { val: "3 Hours", lbl: "Fastest Claim" },
      { val: "200%", lbl: "Max SEV" },
    ],
    salesPitch: "Axis Max Life Smart Term Plan Plus is the only plan in India offering up to 200% of premiums back through its Enhanced Special Exit Value. With the industry's fastest claim settlement (3 hours for eligible cases), cover continuance from just 3 years (vs 5 years industry standard), and Whole Life cover till 100 — this is the premium differentiator for affluent clients who measure value, not just price.",
    keyFeatures: [
      "7 Variants: Regular / Rebalancing / Early ROP Plus / Smart / Whole Life / ROP / Income Protection",
      "Special Exit Value (SEV): 100% premiums from yr 30; Enhanced SEV up to 200% — unique in market",
      "Cover Continuance: After only 3 policy years (industry standard is 5)",
      "Fastest Claim: 3 hours for eligible (SA ≤₹50L, 3 yrs done, docs by 3pm)",
      "Claim Payout Choice: Nominee decides at claim stage — Lump Sum / Income / Mixed",
      "Maternity Cover Add-on: Pregnancy complications + Congenital Anomalies",
      "Policy Loan: Available under ROP, Early ROP Plus, Whole Life variants",
      "Health Management Services (inbuilt): Medical 2nd opinion, consultation"
    ],
    womenDiscount: "15% flat throughout premium paying term",
    salariedDiscount: "8.5% online discount",
    calcUrl: "https://www.axismaxlife.com/term-insurance-plans/smart-term-plan-plus",
    brochureUrl: "https://www.axismaxlife.com/term-insurance-plans/smart-term-plan-plus",
    lastUpdated: "July 2026 (monthly review)"
  },
  {
    id: 4,
    company: "ICICI Prudential Life Insurance Co. Ltd.",
    companyShort: "ICICI Pru",
    bestFor: "Best for: Home loan protection (+100% SA trigger)",
    plan: "iProtect Smart Plus",
    uin: "105N205V04",
    csr: 99.41,
    csrPending: false,
    entryAge: "18 – 65 yrs (Life/Life Plus) / 18 – 45 yrs (Life Rebalancing)",
    maxMaturity: "99 yrs",
    minSA: "₹50 Lakh",
    maxSA: "Unlimited",
    premiumPay: "Single / Regular / Limited",
    limitedPayTerms: "5,7,10,15 yrs / Pay till 60",
    premiumModes: "Annual / Half-yearly / Monthly",
    deathBenefit: "Lump Sum / Income (10 yrs) / Lump Sum + Income / Increasing Income",
    wholeLife: true,
    terminalIllness: true,
    accidentalDeath: true,
    criticalIllness: false,
    wopDisability: false,
    returnOfPremium: false,
    jointLife: false,
    premiumBreak: true,
    smartExit: true,
    spouseCover: false,
    lifeStage: true,
    tags: [
      { label: "Whole Life 99 yrs ✓", type: "yes" },
      { label: "ADB 3× SA ✓", type: "amber" },
      { label: "Home Loan +100% SA ✓", type: "amber" },
      { label: "No Age Cap TI ✓", type: "yes" },
      { label: "Smart Exit ✓", type: "yes" },
      { label: "No CI Rider ✗", type: "no" },
    ],
    keyStats: [
      { val: "99 yrs", lbl: "Max Cover" },
      { val: "3× SA", lbl: "Max ADB" },
      { val: "99.41%", lbl: "CSR FY25" },
    ],
    salesPitch: "ICICI Pru iProtect Smart Plus offers the highest ADB multiplier in the market — 3× Sum Assured. The Home Loan protection trigger (unique +100% SA) and no age cap on Terminal Illness benefit (HDFC caps at 80) make it the strongest pure-risk plan for clients with home loans or HNI profiles. Life Rebalancing variant is a first-of-its-kind structure.",
    keyFeatures: [
      "3 Variants: Life / Life Plus (ADB 3×) / Life Rebalancing (SA grows 25%→100%)",
      "Terminal Illness: No age cap — better than HDFC's age 80 limit",
      "ADB: Max 3× SA (Life Plus) — highest multiplier in market",
      "Life Stage: Marriage (+50%) / Child ×2 (+25% each) / Home Loan (+100%) — unique!",
      "Premium Break: After 5 yrs — multiple times allowed",
      "Smart Exit: After 25th yr, age 60+ — all premiums returned",
      "Insta Claim: ₹3L within 1 working day (SA ≥₹1Cr)",
      "Whole Life coverage till age 99"
    ],
    womenDiscount: "15% on premium rates vs male lives",
    salariedDiscount: "12.5% Regular / 15% Limited Pay (1st year)",
    calcUrl: "https://www.iciciprulife.com/term-insurance/iprotect-smart-plus-plan.html",
    brochureUrl: "https://www.iciciprulife.com/content/dam/icicipru/brochures/ICICI%20Pru%20iProtect%20Smart.pdf",
    lastUpdated: "July 2026 (monthly review) | CSR: FY 2024-25"
  },
  {
    id: 5,
    company: "SBI Life Insurance Company Ltd.",
    companyShort: "SBI Life",
    bestFor: "Best for: Family continuity (Better Half Benefit)",
    plan: "Smart Shield Plus",
    uin: "111N150V01",
    csr: 98.83,
    csrPending: false,
    entryAge: "18 – 60 yrs (Regular) / 18 – 65 yrs (Limited/Single)",
    maxMaturity: "100 yrs",
    minSA: "₹25 Lakh",
    maxSA: "Unlimited",
    premiumPay: "Single / Regular / Limited",
    limitedPayTerms: "10, 15, 20, 25 years",
    premiumModes: "Annual / Half-yearly / Monthly",
    deathBenefit: "Lump Sum / Monthly Instalment option",
    wholeLife: true,
    terminalIllness: false,
    accidentalDeath: true,
    criticalIllness: false,
    wopDisability: false,
    returnOfPremium: false,
    jointLife: false,
    premiumBreak: false,
    smartExit: false,
    spouseCover: true,
    lifeStage: true,
    tags: [
      { label: "Better Half Benefit ✓", type: "yes" },
      { label: "Whole Life 100 yrs ✓", type: "yes" },
      { label: "Future Proofing SA ✓", type: "yes" },
      { label: "SBI Brand Trust ✓", type: "amber" },
      { label: "No Terminal Illness ✗", type: "no" },
      { label: "No Premium Break ✗", type: "no" },
    ],
    keyStats: [
      { val: "100 yrs", lbl: "Max Cover" },
      { val: "Free", lbl: "Spouse Cover" },
      { val: "98.83%", lbl: "CSR FY25" },
    ],
    salesPitch: "SBI Life Smart Shield Plus has one killer differentiator — the Better Half Benefit. After the life assured's death, the spouse gets free cover for 50% of SA for the remaining policy term at zero extra premium. This is a genuine 'two-for-one' protection story. SBI's bancassurance network (22,000+ branches) and brand trust also makes this the easiest sell in Tier 2 and Tier 3 markets.",
    keyFeatures: [
      "3 Variants: Level Cover / Increasing Cover / Future Proofing",
      "Better Half Benefit (inbuilt, free): Spouse gets 50% SA cover for remaining term",
      "Future Proofing: SA auto-increases at key life events — no fresh underwriting",
      "Whole Life option: Coverage till age 100 (Limited Pay only)",
      "Online discount: 7.5% / Salaried discount: 7.5%",
      "SBI brand: 22,000+ branches, highest public trust",
      "Note: No Terminal Illness or Premium Break in this plan"
    ],
    womenDiscount: "Lower rates vs male lives",
    salariedDiscount: "7.5% online discount",
    calcUrl: "https://www.sbilife.co.in/term-insurance/smart-shield-plus",
    brochureUrl: "https://www.sbilife.co.in/term-insurance/smart-shield-plus",
    lastUpdated: "July 2026 (monthly review) | CSR: FY 2024-25"
  },
  {
    id: 6,
    company: "Tata AIA Life Insurance Company Ltd.",
    companyShort: "Tata AIA",
    bestFor: "Best for: Joint life cover (JLP inbuilt)",
    plan: "Sampoorna Raksha Promise",
    uin: "110N176V10",
    csr: 99.41,
    csrPending: false,
    entryAge: "18 – 65 yrs",
    maxMaturity: "100 yrs",
    minSA: "₹50 Lakh (approx.)",
    maxSA: "Unlimited",
    premiumPay: "Single / Regular / Limited",
    limitedPayTerms: "Any term < Policy Term",
    premiumModes: "Annual / Half-yearly / Monthly",
    deathBenefit: "Lump Sum / Monthly Income / Lump Sum + Income",
    wholeLife: true,
    terminalIllness: true,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: true,
    returnOfPremium: false,
    jointLife: true,
    premiumBreak: false,
    smartExit: false,
    spouseCover: false,
    lifeStage: false,
    tags: [
      { label: "Joint Life ✓", type: "yes" },
      { label: "WOP CI Inbuilt ✓", type: "yes" },
      { label: "Whole Life 100 ✓", type: "yes" },
      { label: "Terminal Illness ✓", type: "yes" },
      { label: "WOP ATPD Inbuilt ✓", type: "yes" },
      { label: "Tata+AIA Brand ✓", type: "amber" },
    ],
    keyStats: [
      { val: "100 yrs", lbl: "Max Cover" },
      { val: "99.41%", lbl: "CSR FY25" },
      { val: "Joint", lbl: "Life Cover" },
    ],
    salesPitch: "Tata AIA Sampoorna Raksha Promise is the ideal plan for married couples — the Joint Life option covers both spouses under a single policy. WOP on Critical Illness is inbuilt in Life Promise Plus (not a paid rider), making it exceptional value. Backed by Tata group's domestic trust and AIA's Asian reinsurance expertise, this plan has arguably the strongest brand equity in the private insurance space.",
    keyFeatures: [
      "3 Variants: Life Promise / Life Promise Plus (ADB+CI) / Joint Life",
      "Terminal Illness (inbuilt): Accelerated payout — no age cap",
      "WOP on CI (inbuilt in Life Promise Plus) — not just a rider, free",
      "WOP on ATPD (inbuilt in Life Promise Plus)",
      "Joint Life: Both spouses covered under one policy — unique structure",
      "Whole Life option: Coverage till age 100",
      "Increasing cover: SA increases 5% p.a. (simple)",
      "Online discount: 10% / Salaried: 8.5%"
    ],
    womenDiscount: "Lower rates vs male lives",
    salariedDiscount: "8.5% online discount",
    calcUrl: "https://www.tataaia.com/calculator.html",
    brochureUrl: "https://www.tataaia.com/life-insurance-plans/term-insurance/sampoorna-raksha-promise.html",
    lastUpdated: "July 2026 (monthly review) | CSR: FY 2024-25"
  },
  {
    id: 7,
    company: "Bajaj Life Insurance Co. Ltd.",
    companyShort: "Bajaj Allianz",
    bestFor: "Best for: Critical illness coverage (55 CIs)",
    plan: "Smart Protect Goal",
    uin: "116N163V01",
    csr: 99.04,
    csrPending: false,
    entryAge: "18 – 65 yrs",
    maxMaturity: "99 yrs",
    minSA: "₹50 Lakh",
    maxSA: "Unlimited",
    premiumPay: "Single / Regular / Limited",
    limitedPayTerms: "5, 10, 15, 20, 25, 30 years",
    premiumModes: "Annual / Half-yearly / Quarterly / Monthly",
    deathBenefit: "Lump Sum (base plan)",
    wholeLife: true,
    terminalIllness: false,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: true,
    returnOfPremium: true,
    jointLife: true,
    premiumBreak: false,
    smartExit: false,
    spouseCover: false,
    lifeStage: false,
    tags: [
      { label: "55 CIs — Widest! ✓", type: "amber" },
      { label: "Joint Life ✓", type: "yes" },
      { label: "Whole Life 99 ✓", type: "yes" },
      { label: "ROP Optional ✓", type: "yes" },
      { label: "WOP Disability ✓", type: "yes" },
      { label: "No Terminal Illness ✗", type: "no" },
    ],
    keyStats: [
      { val: "55 CIs", lbl: "CI Coverage" },
      { val: "99 yrs", lbl: "Max Cover" },
      { val: "99.04%", lbl: "CSR FY25" },
    ],
    salesPitch: "Bajaj Allianz Smart Protect Goal covers 55 Critical Illnesses — the most comprehensive CI list in the Indian term insurance market (industry average is 36–42). If a client's primary concern is comprehensive health-linked protection bundled with term cover, this is the strongest answer. Joint Life variant and optional ROP add further versatility for HNI family protection planning.",
    keyFeatures: [
      "3 Variants: Life Cover / Increasing Cover / Joint Life",
      "Critical Illness: 55 conditions — highest in market (vs industry 36–42)",
      "WOP on Disability (WOPB): Add-on rider",
      "Joint Life: Both spouses covered under one policy",
      "Whole Life option: Till age 99 (Limited Pay only)",
      "Return of Premium: Optional add-on — 100% premiums at maturity",
      "Increasing Cover: SA increases 5% p.a. (simple)",
      "Women's rates: Equivalent to male 3 years younger"
    ],
    womenDiscount: "Rates equivalent to male 3 years younger",
    salariedDiscount: "No specific salaried discount",
    calcUrl: "https://www.bajajallianzlife.com/term-insurance/smart-protect-goal-term-plan",
    brochureUrl: "https://www.bajajallianzlife.com/term-insurance/smart-protect-goal-term-plan",
    lastUpdated: "July 2026 (monthly review) | CSR: FY 2024-25"
  },
  {
    id: 8,
    company: "Kotak Mahindra Life Insurance Co. Ltd.",
    companyShort: "Kotak Life",
    bestFor: "Best for: Life stage increases (auto SA hike)",
    plan: "e-Term Plan",
    uin: "107N129V03",
    csr: 98.82,
    csrPending: false,
    entryAge: "18 – 65 yrs",
    maxMaturity: "85 yrs",
    minSA: "₹51 Lakh",
    maxSA: "Unlimited",
    premiumPay: "Single / Regular / Limited",
    limitedPayTerms: "5, 7, 10, 15 yrs / Pay till 60",
    premiumModes: "Annual / Half-yearly / Quarterly / Monthly",
    deathBenefit: "Immediate Lump Sum / Level Recurring Income / Increasing Recurring Income",
    wholeLife: false,
    terminalIllness: false,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: true,
    returnOfPremium: false,
    jointLife: false,
    premiumBreak: false,
    smartExit: true,
    spouseCover: false,
    lifeStage: true,
    tags: [
      { label: "3 Income Payouts ✓", type: "yes" },
      { label: "WOP Inbuilt (Life Secure) ✓", type: "yes" },
      { label: "House Purchase SA+ ✓", type: "amber" },
      { label: "5-yr Anniversary SA+ ✓", type: "amber" },
      { label: "Special Exit ✓", type: "yes" },
      { label: "Max 85 yrs only ✗", type: "no" },
    ],
    keyStats: [
      { val: "3 Types", lbl: "Income Payout" },
      { val: "85 yrs", lbl: "Max Cover" },
      { val: "98.82%", lbl: "CSR FY25" },
    ],
    salesPitch: "Kotak e-Term Plan has the most generous Life Stage triggers in the market — including house purchase and every 5-year anniversary, not just marriage and childbirth. Its 3-payout structure (Immediate / Level Income / Increasing Income) gives nominees maximum flexibility. Life Secure variant has inbuilt WOP on disability — not a paid rider. Best for clients who want structured nominee income.",
    keyFeatures: [
      "3 Variants: Life / Life Plus (ADB max ₹1Cr) / Life Secure (WOP inbuilt)",
      "3 Payout structures: Lump Sum / Level Recurring Income / Increasing Recurring Income",
      "Life Stage Triggers: Marriage / Child / House Purchase / 5-yr Anniversary — most in market",
      "Special Exit: After policy year 25 or 30 — premiums returned",
      "WOP on Disability (inbuilt in Life Secure — not a rider!)",
      "ADB (Life Plus only): Max ₹1 Crore",
      "Online discount: 5% / Salaried: 5%",
      "Note: Max maturity age 85 — lower than most private insurers"
    ],
    womenDiscount: "Special lower premium rates",
    salariedDiscount: "5% discount",
    calcUrl: "https://www.kotaklife.com/online-insurance/term-life-insurance/kotak-e-term-plan",
    brochureUrl: "https://www.kotaklife.com/online-insurance/term-life-insurance/kotak-e-term-plan",
    lastUpdated: "July 2026 (monthly review) | CSR: FY 2024-25"
  },
  {
    id: 9,
    company: "PNB MetLife India Insurance Co. Ltd.",
    companyShort: "PNB MetLife",
    bestFor: "Best for: Child education protection (unique benefit)",
    plan: "Mera Term Plan Plus",
    uin: "117N126V04",
    csr: 99.57,
    csrPending: false,
    entryAge: "18 – 60 yrs (w/o ROP) / 18 – 55 yrs (with ROP)",
    maxMaturity: "99 yrs",
    minSA: "₹25 Lakh",
    maxSA: "Unlimited",
    premiumPay: "Single / Regular / Limited",
    limitedPayTerms: "5, 10, 15, 20 yrs / Pay till 60",
    premiumModes: "Annual / Half-yearly / Quarterly / Monthly",
    deathBenefit: "Lump Sum / Monthly Income / Lump Sum + Monthly Income",
    wholeLife: true,
    terminalIllness: true,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: true,
    returnOfPremium: true,
    jointLife: false,
    premiumBreak: false,
    smartExit: false,
    spouseCover: true,
    lifeStage: true,
    tags: [
      { label: "Child Education Benefit ✓", type: "amber" },
      { label: "WOP CI Inbuilt ✓", type: "yes" },
      { label: "Spouse Cover ✓", type: "yes" },
      { label: "Whole Life 99 ✓", type: "yes" },
      { label: "ROP Optional ✓", type: "yes" },
      { label: "CSR 99.57% ✓", type: "yes" },
    ],
    keyStats: [
      { val: "99.57%", lbl: "CSR FY25" },
      { val: "99 yrs", lbl: "Max Cover" },
      { val: "Child", lbl: "Education SA" },
    ],
    salesPitch: "PNB MetLife Mera Term Plan Plus is the only term plan in India with a Child Education Benefit — SA linked to your child's education milestones. With CSR of 99.57% (among the highest in market), WOP on CI inbuilt in Life Plus Health, spouse coverage add-on, and Whole Life option till 99, this plan competes strongly at every price point. Ideal for young families with education planning needs.",
    keyFeatures: [
      "3 Variants: Life / Life Plus (ADB+CI) / Life Plus Health (ADB+CI+WOP)",
      "Child Education Benefit: SA linked to child's education milestones — unique in market",
      "WOP on CI (inbuilt in Life Plus Health — not just a rider)",
      "WOP on ATPD (inbuilt in Life Plus Health)",
      "Terminal Illness (Life Plus & Life Plus Health variants)",
      "Step-Up: SA increases at Marriage / Child / Education milestones",
      "Spouse Coverage: Add-on option available",
      "ROP: Optional add-on — 100% premiums at maturity",
      "Whole Life option: Till age 99"
    ],
    womenDiscount: "Lower rates vs male lives",
    salariedDiscount: "No specific salaried discount",
    calcUrl: "https://www.pnbmetlife.com/term-insurance/mera-term-plan-plus.html",
    brochureUrl: "https://www.pnbmetlife.com/content/dam/pnb-metlife/docs/product/Download_Brochure/mmtp_plus_brochure.pdf",
    lastUpdated: "July 2026 (monthly review) | CSR: FY 2024-25"
  },
  {
    id: 10,
    company: "Life Insurance Corporation of India",
    companyShort: "LIC",
    bestFor: "Best for: Trust & sovereign guarantee",
    plan: "New Tech-Term Plan",
    uin: "512N351V02",
    csr: 98.15,
    csrPending: false,
    entryAge: "18 – 65 yrs",
    maxMaturity: "80 yrs",
    minSA: "₹50 Lakh",
    maxSA: "Unlimited",
    premiumPay: "Regular / Limited",
    limitedPayTerms: "PT minus 5 yrs / PT minus 10 yrs only",
    premiumModes: "Annual / Half-yearly only",
    deathBenefit: "Lump Sum / Instalment (5 / 10 / 15 equal annual payments)",
    wholeLife: false,
    terminalIllness: false,
    accidentalDeath: false,
    criticalIllness: false,
    wopDisability: false,
    returnOfPremium: false,
    jointLife: false,
    premiumBreak: false,
    smartExit: false,
    spouseCover: false,
    lifeStage: false,
    tags: [
      { label: "Sovereign Guarantee ✓", type: "amber" },
      { label: "Highest Trust Brand ✓", type: "amber" },
      { label: "Competitive Pricing ✓", type: "yes" },
      { label: "No Riders Available ✗", type: "no" },
      { label: "Max 80 yrs only ✗", type: "no" },
      { label: "No Monthly Mode ✗", type: "no" },
    ],
    keyStats: [
      { val: "80 yrs", lbl: "Max Cover" },
      { val: "Govt.", lbl: "Backing" },
      { val: "98.15%", lbl: "CSR FY25" },
    ],
    salesPitch: "LIC New Tech-Term is the only plan backed by a sovereign government guarantee under the LIC Act. For clients who prioritise absolute security over features, LIC's brand trust is unmatched — especially in Tier 2/3 markets and among older age groups. Simple, no-frills structure with competitive online pricing. Best positioned as the 'safe choice' for conservative buyers who reject private insurers.",
    keyFeatures: [
      "2 Plan Options: Level SA / Increasing SA (10% p.a. simple, capped 200%)",
      "Online-only plan — lower premiums vs LIC offline plans",
      "Instalment payout: 5 / 10 / 15 equal annual instalments",
      "Sovereign guarantee: Government-backed under LIC Act — unique in market",
      "Highest brand trust in India — unmatched in rural and semi-urban markets",
      "Non-smoker discount: Lower premium band available",
      "Limitations: Max maturity 80 / No quarterly or monthly mode / No riders / No TI / No ADB"
    ],
    womenDiscount: "Lower rates vs male lives",
    salariedDiscount: "No specific salaried discount",
    calcUrl: "https://licindia.in/lic-s-new-tech-term-954-512n351v01",
    brochureUrl: "https://licindia.in/documents/20121/290753/LIC_New+Tech+Term_Sales+Brochure_4+inch+x+9+inch_Eng+%282%29.pdf/d75b9948-b9e3-2ba1-9886-066a1bee6909",
    lastUpdated: "July 2026 (monthly review) | CSR: FY 2024-25"
  }
,
  {
    id: 11,
    company: "Aditya Birla Sun Life Insurance",
    companyShort: "ABSLI",
    bestFor: "Best for: Maximum flexibility (10 plan options incl. Whole Life)",
    plan: "DigiShield Plan",
    uin: "109N108V13",
    csr: 98.65,
    csrPending: false,
    entryAge: "18 \u2013 65 yrs (Whole Life options: 45 \u2013 65 yrs)",
    maxMaturity: "85 yrs (100 yrs for Whole Life options)",
    minSA: "\u20b930 Lakh (Low Cover variant: \u20b91 \u2013 20 Lakh)",
    maxSA: "Unlimited (subject to underwriting)",
    premiumPay: "Single / Limited / Regular",
    limitedPayTerms: "5,7,10,12,15,20 yrs / Pay till Age 60",
    premiumModes: "Annual / Semi-Annual / Quarterly / Monthly",
    deathBenefit: "Highest of 11\u00d7 Annualized Premium, 105% of Total Premiums Paid, or Effective Sum Assured (Single Pay: 125% of Single Premium)",
    wholeLife: true,
    terminalIllness: true,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: false,
    returnOfPremium: true,
    jointLife: true,
    premiumBreak: false,
    smartExit: false,
    spouseCover: true,
    lifeStage: true,
    tags: [
      { label: "10 Plan Options \u2713", type: "unique" },
      { label: "Whole Life to 100 \u2713", type: "yes" },
      { label: "Terminal Illness \u2713", type: "yes" },
      { label: "Joint Life \u2713", type: "yes" },
      { label: "42 CI Cover \u2713", type: "yes" },
      { label: "ROP (Option 10) \u2713", type: "yes" },
    ],
    keyStats: [
      { val: "10", lbl: "Plan Options" },
      { val: "100 yrs", lbl: "Max Cover (WL)" },
      { val: "6", lbl: "Riders" },
    ],
    salesPitch: "ABSLI DigiShield is the Swiss Army knife of term plans \u2014 10 plan options under one roof, from level cover to whole-life protection to age 100, monthly survival income after 60, and return of premium. When a client's need doesn't fit a standard term template, DigiShield almost always has an option that does. Joint Life covers the spouse in the same policy.",
    keyFeatures: [
      "10 Plan Options: Level / Increasing / Sum Assured Reduction / Whole Life / ROP and more",
      "Whole Life options: cover up to age 100",
      "Terminal Illness (inbuilt): 50% of SA advanced, capped at \u20b92 Cr",
      "Survival Benefit (Option 9): monthly income of 0.12% of SA after age 60",
      "Return of Premium (Option 10) available",
      "Joint Life option \u2014 spouse covered at 50% of Sum Assured in same policy",
      "Enhanced Life Stage Protection: increase cover at Marriage / Childbirth / Home Loan without fresh medicals",
      "ACI Benefit (optional): 42 Critical Illnesses covered",
      "6 optional riders for customisation"
    ],
    womenDiscount: "Lower rates vs male lives",
    salariedDiscount: "See ABSLI Salaried Term Plan",
    calcUrl: "https://lifeinsurance.adityabirlacapital.com/term-insurance/absli-digishield-plan/",
    brochureUrl: "https://lifeinsurance.adityabirlacapital.com/uploads/ABSLI_Digi_Shield_Plan_V13_Brochure_Web_Version_1a00282cef.pdf",
    lastUpdated: "July 2026 (monthly review)"
  },
  {
    id: 12,
    company: "Aditya Birla Sun Life Insurance",
    companyShort: "ABSLI",
    bestFor: "Best for: Salaried professionals (segment-exclusive pricing)",
    plan: "Salaried Term Plan",
    uin: "109N141V05",
    csr: 98.65,
    csrPending: false,
    entryAge: "21 \u2013 55 yrs",
    maxMaturity: "70 yrs",
    minSA: "\u20b950 Lakh",
    maxSA: "Unlimited (subject to underwriting)",
    premiumPay: "Regular / Limited",
    limitedPayTerms: "10, 15 yrs / Pay till Age 60",
    premiumModes: "Annual / Semi-Annual / Quarterly / Monthly",
    deathBenefit: "Higher of 10\u00d7 Annualized Premium, 105% of Total Premiums Paid, or Sum Assured on Death",
    wholeLife: false,
    terminalIllness: true,
    accidentalDeath: true,
    criticalIllness: true,
    wopDisability: false,
    returnOfPremium: true,
    jointLife: false,
    premiumBreak: false,
    smartExit: true,
    spouseCover: false,
    lifeStage: true,
    tags: [
      { label: "Salaried-Only Pricing \u2713", type: "unique" },
      { label: "Terminal Illness \u2713", type: "yes" },
      { label: "ROP Option \u2713", type: "yes" },
      { label: "Early Exit Option \u2713", type: "yes" },
      { label: "42 CI Cover \u2713", type: "yes" },
    ],
    keyStats: [
      { val: "3", lbl: "Plan Options" },
      { val: "\u20b950L+", lbl: "Min Cover" },
      { val: "Salaried", lbl: "Exclusive Segment" },
    ],
    salesPitch: "ABSLI Salaried Term Plan is priced exclusively for the salaried segment \u2014 a cleaner risk pool means sharper premiums than open-market term plans. For a salaried client comparing quotes, this is ABSLI's most competitive answer, with Terminal Illness inbuilt and a Return of Premium option for those who want their money back on survival.",
    keyFeatures: [
      "Exclusively for salaried individuals \u2014 segment-based pricing advantage",
      "3 Plan Options: Life Cover / Life Cover with Early Exit / Life Cover with ROP",
      "Terminal Illness benefit inbuilt",
      "Return of Premium option: 100% of premiums back on survival to maturity",
      "Enhanced Life Stage Protection: increase cover at key life milestones",
      "ACI Benefit (optional): 42 Critical Illnesses covered",
      "Optional riders for accidental death and disability protection"
    ],
    womenDiscount: "Lower rates vs male lives",
    salariedDiscount: "Entire plan is salaried-exclusive",
    calcUrl: "https://lifeinsurance.adityabirlacapital.com/term-insurance/absli-salaried-term-plan/",
    brochureUrl: "https://lifeinsurance.adityabirlacapital.com/uploads/ABSLI_Salaried_Term_Plan_V05_Brochure_Web_Version_9743b6e5d7.pdf",
    lastUpdated: "July 2026 (monthly review)"
  }
];

// ── FEATURE FILTER MAP ──
// Maps filter button data-filter values to plan boolean fields
const FILTER_MAP = {
  "whole-life": "wholeLife",
  "rop":        "returnOfPremium",
  "joint":      "jointLife",
  "ci":         "criticalIllness"
};
