// Data verified: July 2026 (monthly review protocol)
// ULIP CATEGORY — COMPETITOR COMPARISON
// Criteria: One standalone/simple ULIP per company (no combo/multi-benefit bundled variant), no premium restriction
// Base plans: ABSLI Platinum Gain Plan & ABSLI Wealth Infinia
// IRR, rupee amounts (illustration/maturity figures) permanently excluded per compliance rules
// ══════════════════════════════════════════════════════

const ULIP_PLANS = [
  {
    company: 'ABSLI', plan: 'Platinum Gain Plan', uin: '109L142V01',
    isBase: true, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://lifeinsurance.adityabirlacapital.com/ulip-plans/absli-platinum-gain-plan/',
    brochure: 'https://lifeinsurance.adityabirlacapital.com/uploads/ABSLI_Platinum_Gain_Plan_V1_Leaflet_vfadv_ea71a7ae3d.pdf',
    entryAge: '18 – 65 yrs', maturityAge: 'Min 30 / Max 85',
    ppt: 'Limited 5–12 yrs | Regular 10–20 yrs', pt: '10 – 20 yrs',
    saMultiple: '7X or 10X of Annualized Premium',
    fundOptions: 20, portfolioStrategies: 5,
    romc: true, romcNote: 'Return of Mortality + Premium Allocation Charges at maturity',
    loyaltyAdditions: true, loyaltyNote: 'Loyalty Additions from Yr 6/11; Wealth Boosters from Yr 10',
    riders: 'Accidental Death Benefit | Waiver of Premium | Critical Illness | Suraksha Term Plus',
    uniqueFeature: 'Return of Mortality + Premium Allocation Charges at maturity. Wealth Boosters from Year 10. Loyalty Additions from Year 6/11.',
    pitch: 'ABSLI Platinum Gain Plan — ULIP with charge-return structure and wealth boosters, single variant, 20 fund options across 5 investment strategies.',
    keyHighlights: [
      'Return of Mortality Charges + Premium Allocation Charges at maturity',
      'Wealth Boosters added from Year 10 onward',
      'Loyalty Additions from Year 6 (limited/regular) or Year 11',
      '20 fund options across 5 investment strategies',
      '4 optional riders including Suraksha Term Plus',
      'Sum Assured multiple of 7X or 10X annualized premium'
    ],
    fundPerformanceUrl: 'https://lifeinsurance.adityabirlacapital.com/about-us/know-our-funds/',
    verification: 'Verified — Official Brochure V1'
  },
  {
    company: 'ABSLI', plan: 'Wealth Infinia', uin: '109L129V03',
    isBase: true, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://lifeinsurance.adityabirlacapital.com/ulip-plans/absli-wealth-infinia-plan/',
    brochure: 'https://lifeinsurance.adityabirlacapital.com/uploads/ABSLI_Wealth_Infinia_V3_Leaflet_vfadv_9dd124bb66.pdf',
    entryAge: '18 – 65 yrs', maturityAge: 'Legacy: up to 100 | Milestone: up to 85',
    ppt: 'Single | Limited 5–20 yrs | Regular 10–30 yrs', pt: '10 – 30 yrs (Legacy) | Up to 100 minus entry age',
    saMultiple: 'Band-dependent',
    fundOptions: 20, portfolioStrategies: 5,
    romc: true, romcNote: 'Return of Mortality + Premium Allocation Charges at maturity',
    loyaltyAdditions: true, loyaltyNote: 'Loyalty Additions from Yr 6/11; Wealth Boosters from Yr 10',
    riders: 'Accidental Death Benefit | Waiver of Premium | Critical Illness | Suraksha Term Plus | Suraksha Term Rider (base)',
    uniqueFeature: 'Two variants — Legacy (cover till age 100) and Milestone (cover till age 85) — for coverage duration choice. Same charge-return structure as Platinum Gain.',
    pitch: 'ABSLI Wealth Infinia — choice of two coverage-duration variants (Legacy/Milestone), 20 fund options across 5 investment strategies.',
    keyHighlights: [
      'Two variants: Legacy (life cover till age 100) or Milestone (life cover till age 85)',
      'Return of Mortality + Premium Allocation Charges at maturity',
      'Wealth Boosters added from Year 10 onward',
      '20 fund options across 5 investment strategies',
      '5 optional riders — widest rider choice among ABSLI ULIPs',
      'Single, Limited (5-20 yrs), or Regular (10-30 yrs) premium payment terms'
    ],
    fundPerformanceUrl: 'https://lifeinsurance.adityabirlacapital.com/about-us/know-our-funds/',
    verification: 'Verified — Official Brochure V3'
  },
  {
    company: 'ICICI Pru', plan: 'Signature', uin: '105L177V03',
    isBase: false, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://www.iciciprulife.com/ulip-plans/unit-linked-insurance-plans/icici-pru-ulip-signature.html',
    brochure: 'https://www.iciciprulife.com/content/dam/icicipru/brochures/IPru-Signature-Offline-Brochure.pdf',
    entryAge: 'No minimum – 60 yrs (max)', maturityAge: 'Whole Life option: 99 minus entry age',
    ppt: 'Limited 5, 7, 8, 10 yrs | Regular (min 15 yrs) | Whole Life Limited Pay 10 or 15 yrs',
    pt: '15 – 30 yrs, or Whole Life (99 minus entry age)',
    saMultiple: 'Verify from brochure',
    fundOptions: 'Verify from brochure', portfolioStrategies: 4,
    romc: true, romcNote: 'Return of Mortality and Policy Administration Charges at maturity',
    loyaltyAdditions: false, wealthBoosters: true, wealthBoosterNote: 'Wealth Boosters every 5 years starting Year 10',
    riders: 'ICICI Pru Corona Protect Plus Rider',
    uniqueFeature: 'Return of Mortality and Policy Administration Charges at maturity (online purchase). Wealth Boosters every 5 years from Year 10. 4 portfolio strategies.',
    pitch: 'ICICI Pru Signature — award-winning ULIP with charge-return structure and 4 flexible portfolio strategies.',
    keyHighlights: [
      'Return of Mortality + Policy Administration Charges at maturity (online)',
      'Wealth Boosters every 5 years starting from Year 10',
      '4 portfolio strategies for flexible fund allocation',
      'No minimum entry age; maximum entry age 60 years',
      'Whole Life option available (cover till 99 minus entry age)',
      'Unlimited free fund switches'
    ],
    fundPerformanceUrl: 'https://www.iciciprulife.com/fund-performance/all-products-fund-performance-details.html',
    verification: 'Verified — Official Offline Brochure'
  },
  {
    company: 'SBI Life', plan: 'eWealth Plus', uin: '111L147V01',
    isBase: false, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://www.sbilife.co.in/ulip/ewealth-plus',
    brochure: 'https://www.sbilife.co.in/ewealth-plus-brochure',
    entryAge: 'Verify from brochure', maturityAge: 'Verify from brochure',
    ppt: 'Verify from brochure', pt: 'Verify from brochure',
    saMultiple: 'Verify from brochure',
    fundOptions: 12, portfolioStrategies: 2,
    portfolioStrategyNote: 'Growth Strategy (Automatic Asset Allocation) | Active Strategy (self-selected across 12 funds)',
    romc: false,
    loyaltyAdditions: false,
    premiumAllocationCharge: 'None — no premium allocation charge on this plan',
    riders: 'None',
    uniqueFeature: 'No premium allocation charge — full premium invested. Automatic Asset Allocation (AAA) shifts from equity to debt/money-market as policy nears maturity.',
    minPremium: '₹3,000/month (structural minimum, not a benchmark figure)',
    pitch: 'SBI Life eWealth Plus — zero premium allocation charge, hassle-free Automatic Asset Allocation, online-only simple ULIP.',
    keyHighlights: [
      'No Premium Allocation Charge — 100% of premium invested',
      'Automatic Asset Allocation (AAA): higher equity early, shifts to debt/money-market near maturity',
      'Choice of Growth Strategy (passive/automatic) or Active Strategy (12 self-selected funds)',
      'Minimum premium as low as ₹3,000/month',
      'Partial withdrawals available from Year 6',
      'Simple 3-step online buying process'
    ],
    fundPerformanceUrl: 'https://www.sbilife.co.in/customer-services/nav-and-fund-performance',
    verification: 'Verified — Official Brochure (UIN confirmed)'
  },
  {
    company: 'HDFC Life', plan: 'Click 2 Wealth', uin: '101L133V03',
    isBase: false, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://www.hdfclife.com/ulip-plans/click-2-wealth-ulip-plan',
    brochure: 'https://www.hdfclife.com/content/dam/hdfclifeinsurancecompany/products-page/brochure-pdf/hdfc-life-click-2-wealth.pdf',
    entryAge: 'Life Assured: 0 (30 days) – 60 yrs | Proposer (Premium Waiver only): 18 – 65 yrs',
    maturityAge: '18 – 75 yrs (Invest Plus / Premium Waiver) | 99 yrs (Golden Years Benefit)',
    ppt: 'Single Pay | Limited 5, 7, 10 yrs | Regular 10–40 yrs (Golden Years: Limited 10 to 70 minus entry age)',
    pt: '10 – 40 yrs (Invest Plus / Premium Waiver) | 99 minus Age at Entry (Golden Years Benefit — whole of life)',
    saMultiple: 'Regular/Limited: 5X–7X Annualized Premium (age-based) | Single Pay: 1.10X–1.25X Single Premium',
    fundOptions: 18, portfolioStrategies: 'Systematic Transfer Plan (STP) for rupee cost averaging',
    romc: true, romcNote: 'Return of Mortality Charges (ROMC) on maturity',
    loyaltyAdditions: false,
    specialAddition: true, specialAdditionNote: '1% of Annualised Premium as Special Addition to Fund Value for first 5 years',
    planOptions: 'Invest Plus | Premium Waiver | Golden Years Benefit',
    riders: 'HDFC Life Income Benefit on Accidental Disability Rider – Linked (UIN: 101A038V01) — no rider charge',
    riderCount: 1,
    loan: false,
    minPremium: 'Single ₹24,000 | Annual ₹12,000 | Half-yearly ₹6,000 | Quarterly ₹3,000 | Monthly ₹1,000 (structural minimums, not benchmark figures)',
    uniqueFeature: 'Special Addition: 1% of annualised premium added to fund value for first 5 years. Return of Mortality Charges on maturity. Only Fund Management + Mortality charges — no allocation, admin, switching, or discontinuance charges. 3 plan options including Golden Years Benefit (whole-of-life cover to 99 with systematic withdrawal for retirement income).',
    pitch: 'HDFC Life Click 2 Wealth — Special Addition boosts fund value in early years, ROMC on maturity, minimal charge structure with 3 plan options including whole-of-life retirement planning.',
    keyHighlights: [
      'Special Addition: 1% of annualised premium added to Fund Value for first 5 years',
      'Return of Mortality Charges (ROMC) on maturity',
      'Minimal charges — only Fund Management Charge and Mortality Charge (no allocation/admin/switching charges)',
      '18 fund options with unlimited free switching',
      '3 plan options: Invest Plus, Premium Waiver, Golden Years Benefit (whole-of-life to age 99)',
      'No policy loan facility available on this product'
    ],
    fundPerformanceUrl: 'https://www.hdfclife.com/fund-performance',
    verification: 'Verified — Official Brochure (full text fetched)'
  },
  {
    company: 'Kotak Life', plan: 'e-Invest', uin: '107L121V02',
    isBase: false, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://kotaklife.com/online-plans/ulip-plan/kotak-e-invest',
    brochure: 'https://www.kotaklife.com/assets/images/uploads/insurance-plans/Kotak_E_Invest_-_Brochure.pdf',
    entryAge: 'Maximizer: 3–55 yrs | Rising Star: 18–45 yrs | Retire Rich: 3–50 yrs',
    maturityAge: 'Maximizer: 18–75 yrs | Rising Star: 28–60 yrs | Retire Rich: Fixed at 99 yrs',
    ppt: 'Regular or Limited (5, 7, 10 yrs) — combination depends on Plan Option and Policy Term chosen',
    pt: 'Maximizer/Retire Rich: 99 minus Entry Age or fixed 10/12/15/20 yrs | Rising Star: 10 to 60 minus Entry Age',
    saMultiple: '10X Annualized Premium (fixed — same minimum and maximum)',
    fundOptions: 8, fundNames: 'Classic Opportunities | Frontline Equity | Kotak Mid Cap Advantage | Balanced | Dynamic Bond | Dynamic Floating Rate | Dynamic Gilt | Money Market',
    portfolioStrategies: 2, portfolioStrategyNote: 'Self-Managed Strategy | Age Based Strategy',
    romc: true, romcNote: 'Return of Mortality Charges: 25%–200% of total mortality charges (varies by entry age band and Policy Term); not applicable under Rising Star',
    loyaltyAdditions: true, loyaltyNote: '3% of Annual Premium added to fund every year from end of Year 6 (Yearly Additions)',
    planOptions: 'Maximizer | Rising Star | Retire Rich',
    premiumAllocationCharge: 'NIL — no premium allocation charge',
    policyAdminCharge: '₹400/year (structural charge, not a benchmark figure)',
    loan: false,
    minPremium: 'Maximizer/Retire Rich: ₹9,000/yr | Rising Star: ₹18,000/yr (5–7 PPT) or ₹9,000/yr (10 PPT) — structural minimums, not benchmark figures',
    riders: 'None',
    uniqueFeature: 'Rising Star option provides Triple Protection on parent\'s death — lump sum + monthly income (36-120 months) + future premiums waived, policy continues to maturity. Retire Rich covers to age 99 with Systematic Withdrawal retirement income plus a 0.5% p.a. Income Booster. Zero premium allocation charge.',
    pitch: 'Kotak e-Invest — 3 tailored plan options (Maximizer/Rising Star with Triple Protection/Retire Rich with lifetime cover to 99), zero premium allocation charge, Yearly Additions from Year 6.',
    keyHighlights: [
      'Rising Star: Triple Protection on parent\'s death — lump sum + monthly income (36-120 months) + future premiums waived',
      'Retire Rich: Whole-of-life cover to age 99, Systematic Withdrawal retirement income + 0.5% p.a. Income Booster',
      'Zero Premium Allocation Charge',
      'Yearly Additions: 3% of Annual Premium credited every year from end of Year 6',
      'Return of Mortality Charges up to 200% (Maximizer/Retire Rich, age and term dependent)',
      '8 fund options across Self-Managed or Age-Based investment strategy',
      'No policy loan facility on this product'
    ],
    fundPerformanceUrl: 'https://www.kotaklife.com/how-do-i/fund-update',
    verification: 'Verified — Official Brochure (full text fetched)'
  },
  {
    company: 'Tata AIA', plan: 'Fortune Pro', uin: '110L112V07',
    isBase: false, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://www.tataaia.com/life-insurance-plans/wealth-solutions/fortune-pro.html',
    brochure: 'https://www.tataaia.com/content/dam/tataaialifeinsurancecompanylimited/pdf/wealth-solutions/fortune-pro/Fortune-Pro-V4-Brochure.pdf',
    entryAge: '0 (30 days) – 65 yrs',
    maturityAge: '18 – 80 yrs',
    ppt: 'Single Pay | Limited Pay 5–20 yrs | Regular Pay 12–40 yrs', pt: '6 – 40 yrs',
    saMultiple: 'Up to age 49: Single 1.25X SP or Limited/Regular 7X AP | Age 50+: Single 1.10X SP or Limited/Regular 5X AP',
    fundOptions: 'Range of funds rated 4 or 5 stars by Morningstar', portfolioStrategies: 'Enhanced SMART (Systematic Money Allocation & Regular Transfer) strategy',
    romc: false,
    loyaltyAdditions: true, loyaltyNote: 'Regular Loyalty Additions',
    minPremium: 'Single Pay ₹25,000 | Regular/Limited Pay ₹12,000/yr (structural minimums, not benchmark figures)',
    riders: 'Optional riders available — protection or waiver of premium (exact rider names/UINs pending final pass)',
    uniqueFeature: 'Enhanced SMART strategy for structured growth in volatile markets. Life cover up to age 80. All funds rated 4 or 5 stars by Morningstar. Premium redirection at no extra cost. Up to 4 free partial withdrawals after lock-in.',
    pitch: 'Tata AIA Fortune Pro — Enhanced SMART strategy for volatility management, life cover to age 80, funds rated 4-5 stars by Morningstar.',
    keyHighlights: [
      'Enhanced SMART strategy — systematic allocation to manage market volatility',
      'Policy Term flexibility: 6 to 40 years',
      'Life cover up to age 80',
      'All funds rated 4 or 5 stars by Morningstar',
      'Free premium redirection to different funds',
      'Up to 4 free partial withdrawals after lock-in period',
      'Regular Loyalty Additions to boost investments'
    ],
    fundPerformanceUrl: 'https://www.tataaia.com/investment-funds/tata-aia-fund-performance.html',
    verification: 'Verified — Official product page (full data fetched, entry age conflict resolved: max is 65 yrs)'
  },
  {
    company: 'Bajaj Life', plan: 'Goal Assure IV', uin: '116L204V01',
    isBase: false, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://www.bajajlifeinsurance.com/ulip-plans/financial-life-goals-assure.html',
    brochure: 'https://www.bajajlifeinsurance.com/content/dam/balic-web/pdf/ulip/goal-assure-brochure.pdf',
    entryAge: '0 – 60 yrs', maturityAge: '18 – 75 yrs',
    ppt: 'PT10: 5,7,10 yrs | PT15: 5,7,10,15 yrs | PT20: 5,7,10,15,20 yrs', pt: '10 | 15 | 20 yrs (fixed options)',
    saMultiple: 'Min: Age<50: 7X AP | Age 50+: 5X AP — Max varies by age band and Policy Term',
    fundOptions: 30, portfolioStrategies: 4,
    portfolioStrategyNote: 'Investor Selectable | Wheel of Life (glide path by years-to-maturity) | Trigger Based (secures gains) | Auto Transfer (systematic monthly transfer)',
    romc: true, romcNote: 'Return of Mortality Charges at maturity',
    loyaltyAdditions: true, loyaltyNote: 'Loyalty Additions at Yr 10 (1.00%), Yr 15 (1.50%), Yr 20 (2.00%) of avg fund value',
    fundBooster: true, fundBoosterNote: 'Fund Booster 2% of average daily fund value (last 3 yrs) at maturity — for Policy Term 10 yrs or greater',
    familyBenefit: true, familyBenefitNote: 'Additional maturity benefit (0.5%–1%) if a family member is an existing Bajaj Life customer',
    minPremium: 'Yearly ₹36,000 | Half-yearly ₹18,000 | Quarterly ₹9,000 | Monthly ₹3,000 | Top-up ₹5,000 (structural minimums, not benchmark figures)',
    riders: 'Bajaj Life Linked Accident Protection Rider II (UIN: 116A057V02) | Bajaj Life Care Plus Rider (UIN: 116A059V01) | Bajaj Life Linked New Critical Illness Benefit Rider (UIN: 116A060V01)',
    premiumAllocationCharge: 'NIL',
    uniqueFeature: '4 distinct portfolio strategies including Wheel of Life (automatic age-based glide path) and Trigger Based (locks in gains on 15% market upswings). Fund Booster at maturity for 10+ year terms. Family Benefit rewards existing Bajaj Life customer households.',
    pitch: 'Bajaj Life Goal Assure IV — 4 portfolio strategies including auto-glide and gain-locking options, Fund Booster + Loyalty Additions + ROMC at maturity, zero allocation charge.',
    keyHighlights: [
      '4 portfolio strategies: Investor Selectable, Wheel of Life (auto glide-path), Trigger Based (locks gains), Auto Transfer',
      'Fund Booster: 2% of average fund value added at maturity (Policy Term 10+ yrs)',
      'Loyalty Additions at Year 10, 15, and 20 (1.00%/1.50%/2.00%)',
      'Return of Mortality Charges at maturity',
      'Family Benefit for existing Bajaj Life customer households',
      'Zero Premium Allocation Charge',
      '3 riders available including Critical Illness and Accident Protection'
    ],
    fundPerformanceUrl: 'https://www.bajajlifeinsurance.com/fund-performance.html',
    verification: 'Verified — Official Brochure (full text fetched)'
  },
  {
    company: 'Axis Max Life', plan: 'Online Savings Plan Plus (Wealth Variant)', uin: '104L131V01',
    isBase: false, type: 'ULIP Non-Par', status: 'Active — launched Jan 2026, replaces earlier Online Savings Plan (104L098V06)',
    url: 'https://www.axismaxlife.com/investment-plans/ulip-plans/wealth-investment-plan',
    brochure: 'https://www.axismaxlife.com/static-page/assets/homepage/104L131V01_Online-Savings-Plan-Plus-Prospectus_Withdrawn.pdf',
    entryAge: 'Single Pay: 0 (31 days) – 65 yrs (varies 35–65 by cover multiple) | Limited/Regular Pay: 0 (31 days) – 65 yrs (varies 42–65 by cover multiple)',
    maturityAge: 'Min 18 yrs | Max 85 yrs (Limited/Regular Pay, all cover multiples)',
    ppt: 'Single Pay | Limited/Regular Pay 5–10 yrs (depends on entry age/maturity age combination)',
    pt: 'Single Pay: 10–20 yrs | Limited/Regular Pay: 10–85 yrs',
    saMultiple: 'Cover multiples 1.25X–20X depending on entry age band and pay mode',
    fundOptions: 22, portfolioStrategies: 5,
    portfolioStrategyNote: 'Self-Managed | Systematic Transfer Plan | Lifecycle Based (age-glide) | Trigger Based (locks gains) | Dynamic Fund Allocation (years-to-maturity glide)',
    romc: false,
    returnOfCharges: true, returnOfChargesNote: 'Return of 125%–150% of total Policy Administration Charges at maturity (based on Policy Term)',
    loyaltyAdditions: false,
    womenBenefit: true, womenBenefitNote: 'Women Empowerment Benefit — 1% of Annualized Premium (or 0.5% of Single Premium) added to Fund Value at first year allocation',
    existingCustomerBenefit: true, existingCustomerBenefitNote: '2.5% (PT<20 yrs) or 5.0% (PT 20+ yrs) of premium added at maturity for existing Axis Max Life customers',
    premiumAllocationCharge: 'NIL',
    loan: false,
    minPremium: 'Single Pay ₹2,00,000 | Annual ₹6,000 | Semi-Annual ₹3,000 | Quarterly ₹1,500 | Monthly ₹500 (structural minimums, not benchmark figures)',
    riders: 'Axis Max Life Critical Illness and Disability Secure Rider (UIN: 104A034V02) | Axis Max Life Smart Ultra Protect Rider (UIN: 104A049V02) — 4 benefit variants including Term Booster, Accidental Death, Accidental Disability, Payor Benefit',
    uniqueFeature: '5 plan variants (Wealth shown here; also Wealth Whole Life, Gold, Platinum, Titanium with premium-funding protection built in). Women Empowerment Benefit adds extra allocation for female policyholders. Zero premium allocation charge with Return of up to 150% of Policy Admin Charges at maturity.',
    pitch: 'Axis Max Life Online Savings Plan Plus — zero allocation charge, Women Empowerment Benefit, up to 150% Policy Admin Charge return at maturity, 22 funds across 5 strategies.',
    keyHighlights: [
      'Zero Premium Allocation Charge on all variants',
      'Return of 125%–150% of total Policy Administration Charges at maturity',
      'Women Empowerment Benefit — extra fund allocation exclusively for female policyholders',
      'Existing Customer Benefit — 2.5%–5% booster for existing Axis Max Life customers',
      '22 fund options across 5 investment strategies including Lifecycle-based auto glide path',
      'Smart Withdrawals — systematic income stream up to 12% p.a. of fund value',
      '5 plan variants for different life-stage needs (Wealth, Wealth Whole Life, Gold, Platinum, Titanium)'
    ],
    fundPerformanceUrl: 'https://www.axismaxlife.com/fund-performance',
    verification: 'Verified — Official Prospectus (full text fetched); note company also has an older "Online Savings Plan" (104L098V06) still referenced on some pages — this entry uses the newer, fully-documented Plus variant'
  },
  {
    company: 'PNB MetLife', plan: 'Goal Ensuring Multiplier (Wealth Option)', uin: '117L133V09',
    isBase: false, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://www.pnbmetlife.com/insurance-plans/long-term-savings/pnb-metlife-goal-ensuring-multiplier.html',
    brochure: 'https://www.pnbmetlife.com/content/dam/pnb-metlife/docs/product/Download_Brochure/GEM_Brochure.pdf',
    entryAge: 'Single Life: 0 (30 days) – 60 yrs | Joint Life: 0 (30 days) – 55 yrs (both lives)',
    maturityAge: 'Other than Whole Life: max 90 yrs | Whole Life: max 99 yrs | Joint Life: max 65 yrs',
    ppt: 'Single Life (Other than Whole Life): Single Pay | Regular Pay | 5/7/10 Pay | Whole Life: Regular/7/10 Pay | Joint Life: Single Pay only',
    pt: 'Single Life: Other than Whole Life 10–30 yrs | Whole Life min 39 yrs | Joint Life: 10 yrs',
    saMultiple: 'Sum Assured = Single Pay/Annualized Premium × Sum Assured Multiple chosen at inception',
    fundOptions: 20, portfolioStrategies: 3,
    portfolioStrategyNote: 'Self-Managed Strategy | Systematic Transfer Strategy | Life-Stage Strategy (age-based glide)',
    romc: true, romcNote: 'Return of Charges: Return of Fund Management Charges (ROFMC) + Return of Premium Allocation Charges (ROPAC, up to 150%) + Return of Mortality Charges (ROMC, not for Single Pay)',
    loyaltyAdditions: false,
    fundBooster: true, fundBoosterNote: 'Regular/5/7/10 Pay: 1% at Yr15,20,25,30 | Single Pay: 2.4% at Yr10,15,20,25,30',
    minPremium: 'Single Pay ₹20,000 | Minimum Annualized Premium ₹18,000 (structural minimums, not benchmark figures)',
    riders: 'PNB MetLife Linked Accidental Death Benefit Rider (UIN: 117A024V01)',
    uniqueFeature: 'Triple charge-return structure (ROFMC + ROPAC + ROMC) — among the most comprehensive charge-return mechanisms in the category. Joint Life coverage option available on two lives under Single Pay. Also available in 4 other variants (Wealth+Care, Goal Assured, Income Assured, Smart Child) with built-in protection features for different life goals.',
    pitch: 'PNB MetLife Goal Ensuring Multiplier — triple return of charges (fund management + allocation + mortality), 20 funds, Joint Life option, Fund Boosters through Year 30.',
    keyHighlights: [
      'Triple Return of Charges: Fund Management + Premium Allocation (up to 150%) + Mortality Charges',
      'Fund Boosters at Year 15/20/25/30 (Regular Pay) or Year 10/15/20/25/30 (Single Pay)',
      'Joint Life coverage available on two lives under Single Pay',
      '20 fund options across 3 investment strategies including Life-Stage age-based glide',
      'Whole Life option available — cover to age 99',
      '4 additional plan variants for specific life goals (Wealth+Care, Goal Assured, Income Assured, Smart Child)'
    ],
    fundPerformanceUrl: 'https://www.pnbmetlife.com/investments/funds-performance/all-funds.html',
    verification: 'Verified — Official product page (UIN conflict resolved: confirmed current version is V09, full eligibility table fetched)'
  },
  {
    company: 'Canara HSBC', plan: 'Promise4Growth Plus', uin: '136L093V01',
    isBase: false, type: 'ULIP Non-Par', status: 'Active',
    url: 'https://www.canarahsbclife.com/ulips/promise4growth-plus',
    brochure: 'https://www.canarahsbclife.com/content/dam/chli/pdf/promise4growth-plus/product-brochure.pdf',
    entryAge: 'Promise4Wealth Plus: 0–65 yrs | Promise4Care Plus: PPT<10: 18–45 | PPT≥10: 18–50 | Promise4Life Plus: PPT<10: 18–55 | PPT≥10: 18–65',
    maturityAge: 'Promise4Wealth Plus: 18–80 yrs | Promise4Care Plus: PPT<10: 28–70 | PPT≥10: 28–75 | Promise4Life Plus: up to age 100',
    ppt: 'Limited Pay 5 to (PT-1) yrs | Regular Pay same as PT', pt: 'Promise4Wealth Plus: 10–30 yrs | Promise4Care Plus: 10–25 yrs | Promise4Life Plus: 100 minus Age at entry',
    saMultiple: '10X Annualized Premium',
    fundOptions: 15, portfolioStrategies: 4,
    portfolioStrategyNote: 'Systematic Transfer Option | Return Protector Option | Auto Funds Rebalancing | Safety Switch Option',
    romc: true, romcNote: 'Mortality Charges deducted during Policy Term added back to Fund Value at maturity',
    loyaltyAdditions: true, loyaltyNote: 'Loyalty Additions every 5th year from Yr5 through PPT; Wealth Boosters every 5th year from Yr10 through PT',
    planOptions: 'Promise4Wealth Plus | Promise4Care Plus | Promise4Life Plus',
    withdrawalOptions: 'Milestone Withdrawal Option (20% of fund value every 5 yrs from Yr10) | Systematic Withdrawal Option | Partial Withdrawals free from Yr6',
    premiumFundingBenefit: true, premiumFundingBenefitNote: 'Promise4Care Plus only — Company funds all future premiums on death, plus monthly income of 1/12 of Annualized Premium for up to 120 months',
    minPremium: '₹12,000 – No Limit (structural minimum, not a benchmark figure)',
    riders: 'Verify from brochure',
    uniqueFeature: '3 variants for different life stages, including Promise4Care Plus (Premium Funding Benefit + monthly income on death) and Promise4Life Plus (cover to age 100). Milestone Withdrawal Option releases 20% of fund value every 5 years from Year 10.',
    pitch: 'Canara HSBC Promise4Growth Plus — 3 variants from simple wealth-building to whole-of-life cover with Premium Funding Benefit on death.',
    keyHighlights: [
      '3 plan options: Promise4Wealth Plus, Promise4Care Plus (Premium Funding Benefit), Promise4Life Plus (cover to age 100)',
      'Return of Mortality Charges at maturity',
      'Milestone Withdrawal Option — 20% of fund value released every 5 years from Year 10',
      'Loyalty Additions every 5 years from Year 5; Wealth Boosters every 5 years from Year 10',
      '15 fund options across 4 portfolio management strategies',
      'Only Fund Management + Risk Charges levied — no premium allocation or policy admin charges'
    ],
    fundPerformanceUrl: 'https://www.canarahsbclife.com/funds-navs/fund-performance',
    verification: 'Verified — Official product page (full eligibility table fetched)'
  },
  {
    company: 'LIC', plan: 'Nivesh Plus (Plan 849)', uin: '512L317V01',
    isBase: false, type: 'ULIP Non-Par, Single Premium', status: 'Active',
    url: 'https://licindia.in/unit-linked-plans',
    brochure: 'https://licindia.in/documents/20121/103490/LIC_Nivesh+Plus+_Sales+Brochure+Eng..pdf',
    entryAge: 'Option 1: up to 70 yrs | Option 2: up to 35 yrs', maturityAge: 'Verify from brochure',
    ppt: 'Single Premium only', pt: 'Verify from brochure',
    saMultiple: 'Option 1: 1.25X Single Premium | Option 2: 10X Single Premium',
    fundOptions: 4, fundNames: 'Growth Fund | Balanced Fund | Secured Fund | Bond Fund',
    portfolioStrategies: 'Verify from brochure',
    romc: false,
    loyaltyAdditions: false,
    guaranteedAdditions: true, guaranteedAdditionsNote: 'Fixed percentage of single premium credited as Guaranteed Additions during the policy term',
    riders: 'Linked Accidental Death Benefit Rider',
    uniqueFeature: 'Single premium only — no recurring premium commitment. Two Sum Assured options (1.25X for lower charges, 10X for higher cover and tax exemption). Guaranteed Additions credited during the term.',
    pitch: 'LIC Nivesh Plus — single-premium ULIP with Guaranteed Additions, choice of 2 sum assured options, LIC brand trust.',
    keyHighlights: [
      'Single Premium plan — no recurring premium commitment',
      'Guaranteed Additions: fixed % of single premium credited during the policy term',
      'Two Sum Assured options: 1.25X (lower charges) or 10X (higher cover, tax exemption)',
      '4 fund options: Growth, Balanced, Secured, Bond',
      'Up to 12 free fund switches per year',
      'Partial withdrawals after 5-year lock-in'
    ],
    fundPerformanceUrl: 'https://licindia.in/plan-nav1',
    verification: 'Partially Verified — UIN, entry age options and SA multiples confirmed; maturity age/PT pending final brochure pass'
  }
];
